version: '3.3'

services:
  symlex-demo:
    image: symlex/demo:latest
    build:
      context: ./
      dockerfile: ./docker/demo/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - symlex-mysql
      - symlex-redis

  symlex-redis:
    image: redis:3-alpine

  symlex-mysql:
    image: symlex/mysql:5.7
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512