parameters:
    app.name: 'Symlex'
    app.version: '4.2'
    app.url: 'https://demo.symlex.org/'
    app.email: hello@symlex.org
    app.locale: en
    db.host: symlex-mysql
    db.port: 3306
    db.name: web
    db.user: web
    db.password: web
    redis.host: symlex-redis
    redis.port: 6379
    mailer.host: null
    mailer.port: null
    mailer.encryption: null
    mailer.username: ''
    mailer.password: ''
    mailer.auth_mode: ''