version: '3'

services:
    web:
        build:
            context: ./
            dockerfile: ./app/docker/nginx/Dockerfile
        ports:
            - "8081:80"
        depends_on:
            - php
        volumes:
            - ./:/var/www/html
            - ./app/docker/nginx/site.conf:/etc/nginx/conf.d/default.conf

    php:
        build:
            context: ./
            dockerfile: ./app/docker/php/Dockerfile
        depends_on:
            - db
            - redis
            - mailhog
            - webdriver
        volumes:
            - ./:/var/www/html
            - node-data:/var/www/html/frontend/node_modules

    db:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: web
            MYSQL_PASSWORD: web
            MYSQL_DATABASE: web

    redis:
        image: redis:3-alpine

    mailhog:
        image: mailhog/mailhog
        ports:
            - "8082:8025"

    webdriver:
        image: selenium/standalone-chrome
        volumes:
          - /dev/shm:/dev/shm

volumes:
    node-data:
        driver: local
    mysql-data:
        driver: local

networks:
    default:
        driver: bridge